-- MySQL Script generated by MySQL Workbench
-- sam. 23 avril 2022 02:00:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BeeBrave
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BeeBrave
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BeeBrave` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `BeeBrave` ;

-- -----------------------------------------------------
-- Table `BeeBrave`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BeeBrave`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(255) NULL,
  `firstname` VARCHAR(255) NULL,
  `mail` VARCHAR(255) NULL,
  `password` VARCHAR(45) NULL,
  `beez` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeeBrave`.`journey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BeeBrave`.`journey` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `start` VARCHAR(45) NULL,
  `end` VARCHAR(45) NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 'coming',
  `startingpoint` VARCHAR(255) NULL,
  `arrivalpoint` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeeBrave`.`user_has_journey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BeeBrave`.`user_has_journey` (
  `user_id` INT NOT NULL,
  `journey_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `journey_id`),
  INDEX `fk_user_has_journey_journey1_idx` (`journey_id` ASC) VISIBLE,
  INDEX `fk_user_has_journey_user_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_journey_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `BeeBrave`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_journey_journey1`
    FOREIGN KEY (`journey_id`)
    REFERENCES `BeeBrave`.`journey` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeeBrave`.`association`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BeeBrave`.`association` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `creationdate` DATE NOT NULL,
  `sector` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BeeBrave`.`donations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BeeBrave`.`donations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `association_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `amount` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_donations_user1_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  INDEX `fk_donations_association1_idx` (`association_id` ASC) VISIBLE,
  CONSTRAINT `fk_donations_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `BeeBrave`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_donations_association1`
    FOREIGN KEY (`association_id`)
    REFERENCES `BeeBrave`.`association` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
